### ISSUE TITLE
how to speed up search on large text columns?

### ISSUE THREAD

**Issue by MiroBabic** [textacular/textacular#105]
I need to do full-text search on large text columns. Even I have gin indexes on them (and standard indexes on other searchable columns) search in table with 21k rows takes 5-6 seconds if I enable search on 2 big columns.
Is there any way how to speed this up?

**Comment by gregmolnar** [comment]
That shouldn't be that slow in my experiences. How big are those tables?

**Comment by MiroBabic** [comment]
Table size with all indexes has about 200MB, 21k rows. When I removed from search 2 columns with large text, search is pretty fast for other string values. In those 2 columns length of text is up to 20k characters

**Comment by simi** [comment]
I think there's nothing that can be done in library. Thanks for sharing your solution @MiroBabic. Can be this issue closed now?
