### ISSUE TITLE
"count" method not working results from searches

### ISSUE THREAD

**Issue by welkie** [textacular/textacular#117]
I noticed that when doing a basic search, I get back a ```ModelName::ActiveRecord_Relation``` object:

```
> Post.basic_search('apple').class
 => Post::ActiveRecord_Relation 
```

And this is the same object type returned by a regular ActiveRecord method call:

```
> Post.all.class
 => Post::ActiveRecord_Relation 
```

I can call ```count``` on the results of the ```all``` method:

```
> Post.all.count
   (0.7ms)  SELECT COUNT(*) FROM "posts"
 => 500 
```

But doing so on the results of the ```basic_search``` method doesn't work. It complains about a syntax error:

```
> Post.basic_search('apple').count
   (0.5ms)  SELECT COUNT("posts".*, COALESCE(ts_rank(to_tsvector('english', "posts"."title"::text), plainto_tsquery('english', 'apple'::text)), 0) + COALESCE(ts_rank(to_tsvector('english', "posts"."body"::text), plainto_tsquery('english', 'apple'::text)), 0) AS "rank84513494173201649") FROM "posts" WHERE (to_tsvector('english', "posts"."title"::text) @@ plainto_tsquery('english', 'apple'::text) OR to_tsvector('english', "posts"."body"::text) @@ plainto_tsquery('english', 'apple'::text))
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "AS"
LINE 1: ...), plainto_tsquery('english', 'apple'::text)), 0) AS "rank84...
                                                             ^
: SELECT COUNT("posts".*, COALESCE(ts_rank(to_tsvector('english', "posts"."title"::text), plainto_tsquery('english', 'apple'::text)), 0) + COALESCE(ts_rank(to_tsvector('english', "posts"."body"::text), plainto_tsquery('english', 'apple'::text)), 0) AS "rank84513494173201649") FROM "posts" WHERE (to_tsvector('english', "posts"."title"::text) @@ plainto_tsquery('english', 'apple'::text) OR to_tsvector('english', "posts"."body"::text) @@ plainto_tsquery('english', 'apple'::text))
	from (irb):19
```

Though oddly enough, the ```length``` method does work:

```
> Post.basic_search('apple').length
  Post Load (11.5ms)  SELECT "posts".*, COALESCE(ts_rank(to_tsvector('english', "posts"."title"::text), plainto_tsquery('english', 'apple'::text)), 0) + COALESCE(ts_rank(to_tsvector('english', "posts"."body"::text), plainto_tsquery('english', 'apple'::text)), 0) AS "rank4506636060754842" FROM "posts" WHERE (to_tsvector('english', "posts"."title"::text) @@ plainto_tsquery('english', 'apple'::text) OR to_tsvector('english', "posts"."body"::text) @@ plainto_tsquery('english', 'apple'::text)) ORDER BY "rank4506636060754842" DESC
 => 132
```

I was wondering if this is intentional design or if this may be a bug?

My setup:

Rails 5.1.3
Postgres 9.6.4

**Comment by gregmolnar** [comment]
The difference between `count` and `length` is the later counts the number of items in the resulting collection whereas `count` performs a count query in the database and it looks like the way the query is generated results in a SQL error. I will check whether we can fix it or not when I get some time.

**Comment by welkie** [comment]
That makes sense. I'll try to look into the SQL error myself soon too.

**Comment by adeeb1** [comment]
Any updates on this? I just upgraded to Rails 5.1.4, and I'm unable to display pagination with [kaminari](https://github.com/kaminari/kaminari) because one of its helpers uses the `count` method. I know the issue is not Kaminari because I receive an error message similar to this without any pagination.

```
users = User.fuzzy_search({ name: '@test.com', email: '@test.com' }, false)
users.count
```

The code above returns the following:

```
   (1.0ms)  SELECT COUNT("users".*, COALESCE(similarity("users"."name", '@test.com'), 0) + COALESCE(similarity("users"."email", '@test.com'), 0) AS "rank48914057553066791") FROM "users" WHERE (("users"."name" % '@test.com') OR ("users"."email" % '@test.com'))
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "AS"
LINE 1: ...ESCE(similarity("users"."email", '@test.com'), 0) AS "rank48...
                                                             ^
: SELECT COUNT("users".*, COALESCE(similarity("users"."name", '@test.com'), 0) + COALESCE(similarity("users"."email", '@test.com'), 0) AS "rank48914057553066791") FROM "users" WHERE (("users"."name" % '@test.com') OR ("users"."email" % '@test.com'))
```

**Comment by gregmolnar** [comment]
@adeeb1 I will have a look on this issue in the coming days.

**Comment by aaronchi** [comment]
I'm also having this issue

**Comment by gregmolnar** [comment]
I know this issue is open for quite a while, but I am buried in tasks unfortunately. I will try to find some time to release a fix soon.

**Comment by Shpigford** [comment]
Also having this issue.

**Comment by gregmolnar** [comment]
@Shpigford You can do something like:

```
Foobar.basic_search("bar").count(:id)
```

@adeeb1 This is an old issue, so maybe kaminari has changed since, but I looked at it know and it uses `count(:all)` which drops the custom select from textacular and that prevents the syntax error. So all should be fine. Let me know if it is still broken for you

**Comment by adeeb1** [comment]
@jgujgu I've been making two queries: one for the IDs of the records, and one for the records. That way, the `count` will work:

```
user_ids = User.fuzzy_search({ name: '@test.com', email: '@test.com' }, false).pluck(:id)
users = User.where(id: user_ids)
```

If you need the results to be ordered, you can use PostgreSQL's [`array_position`](https://www.postgresql.org/docs/9.5/functions-array.html#ARRAY-FUNCTIONS-TABLE) to preserve the order efficiently:

```
user_ids = User.fuzzy_search({ name: '@test.com', email: '@test.com' }, false).pluck(:id)
order_by = "array_position(ARRAY[#{user_ids.join(',')}]::int[], users.id::int)"
users = User.where(id: user_ids).order(order_by)
```

That's the workaround I've been using.
