### ISSUE TITLE
Deprecation warning in Rails 5.2

### ISSUE THREAD

**Issue by davidwessman** [textacular/textacular#120]
When trying out the Rails 5.2 rc1 I found a deprecation warning regarding `Dangerous query methods`.
```
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "\"rank69904827133326868\" DESC". 
Non-attribute arguments will be disallowed in Rails 6.0. 
This method should not be called with user-provided values, such as request parameters or model attributes. 
Known-safe values can be passed by wrapping them in Arel.sql(). 
(called from assemble_query at .../.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/textacular-5.0.1/lib/textacular.rb:128)
```

The issue comes from the `assemble_query` method found [here](https://github.com/textacular/textacular/blob/master/lib/textacular.rb#L128).

With some guidance on how to handle the random column name I could try to patch it.
Perhaps we can use the `Arel.sql()`-wrapping suggestion? I am however not sure what it would impact.

**Comment by cblackburn-ajla** [comment]
I am also seeing this warning and interested in a solution.  Regarding impact, I assume it will be negligible from a performance perspective.  Knowing that it will be `disallowed` in Rails 6 provides some extra motivation.  @davidwessman, if you want to take a stab at it I'll wait for your patch. If not, please ping me here and I'll give it a shot.

**Comment by davidwessman** [comment]
@cblackburn-ajla 
I just played around with using `Arel.sql()` and managed to remove some deprecations, but please go ahead

**Comment by davidwessman** [comment]
@cblackburn-ajla Please checkout my PR :) #121
