### ISSUE TITLE
Disable ranking?

### ISSUE THREAD

**Issue by Shpigford** [textacular/textacular#124]
Is it possible to disable ranking of results?

I have the following ActiveRecord query:

    Artist.basic_search(genres: 'southern rock').left_joins(:follows).group(:id).order('COUNT(follows.artist_id) DESC').limit(10)

And the SQL output of that is...

```sql
SELECT  "artists".*, COALESCE(ts_rank(to_tsvector('english', "artists"."genres"::text),
  to_tsquery('english', 'southern\ rock'::text)), 0) AS "rank41973923120014518" FROM
  "artists" LEFT OUTER JOIN "follows" ON "follows"."artist_id" = "artists"."id" WHERE
  (to_tsvector('english', "artists"."genres"::text) @@ to_tsquery('english', 'southern\
  rock'::text)) GROUP BY "artists"."id" ORDER BY "rank41973923120014518" DESC, COUNT(follows.artist_id)
  DESC LIMIT 10
```

Unfortunately, it's ordering first by `rank41973923120014518` instead of by `COUNT(follows.artist_id)`.

So, is there some way to have the ORDER BY disregard the ranking?

**Comment by gregmolnar** [comment]
I don't think there is a way to achieve that at the moment, but I can imagine that as a feature. I am quite short on time these days, but I will try have a look at implementing that shortly.

**Comment by gregmolnar** [comment]
@Shpigford Actually, this can do the trick:

```ruby
Artist.basic_search(genres: 'southern rock').left_joins(:follows).group(:id).reorder('').order('COUNT(follows.artist_id) DESC').limit(10)

```
