### ISSUE TITLE
Rails 6 Support

### ISSUE THREAD

**Issue by zbuttram** [textacular/textacular#126]
Was attempting to try out the latest beta since 6 should be releasing soon, but it looks like the Gemfile requires ActiveRecord >=5, <6 right now. Doesn't look like there have been any breaking changes to ActiveRecord at least as far as I can tell. Is there a decent way of getting a version that will allow ActiveRecord 6 so I can test?

Going to fork and try having bundler pull from git, but I'm not sure if that will work.

**Comment by gregmolnar** [comment]
>  Is there a decent way of getting a version that will allow ActiveRecord 6 so I can test?

I changed the dependency requirement and now you can use master to test with Active Record 6:
```
gem 'textacular', git: 'git://github.com/textacular/textacular'
```

I will release a new version when Rails 6 is released.
