### ISSUE TITLE
Create Trigram Migration appends [5.0] even on older Rails

### ISSUE THREAD

**Issue by stevehill1981** [textacular/textacular#131]
I'm running Rails 4.2.11.1 (I know, I know). I just installed version 4.0.1 and ran `rake textacular:create_trigram_migration`. This was the output.

```ruby
class InstallTrigram < ActiveRecord::Migration[5.0]
  def self.up
    ActiveRecord::Base.connection.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
  end

  def self.down
    ActiveRecord::Base.connection.execute("DROP EXTENSION pg_trgm;")
  end
end
```

Expected output should not contain the `[5.0]`, that was added in Rails 5.0. I appreciate I might be using an unsupported version of the gem now. Not a problem, since I can fix by manually editing the migration for now.

**Comment by simi** [comment]
Rails 5.0 is currently the lowest supported version in master. I think it is ok as is.

**Comment by stevehill1981** [comment]
Thanks, @simi. I appreciate the amount of effort involved in supporting outdated versions of Rails. I'll close this.
