### ISSUE TITLE
Documentation Site 404s

### ISSUE THREAD

**Issue by andyatkinson** [textacular/textacular#153]
The linked documentation site is is a 404. Did it move?

I'm just looking into this gem for the first time as I'm looking for actively maintained gems that have existing support for some of the PostgreSQL Full Text Search capabilities. It would be nice to fix some of the small broken windows like the documentation site and the pill graphic on the main readme that's a broken image link.

**Comment by andyatkinson** [comment]
Hi @gregmolnar - since we sort of know each other - I figured I'd ping you directly - are you still working on this gem and are you using it in production applications? Thanks.

**Comment by gregmolnar** [comment]
Hey @andyatkinson 
Yes, I still maintain it and use it. I will check the above errors and fix them.

**Comment by andyatkinson** [comment]
@gregmolnar Cool, no worries! I'm evaluating this gem, ransack, pg_search, and possibly creating a new one. My ideal gem is PG only (modern versions), has most everything expressed as SQL, possibly PL/PgSQL functions, triggers, GIN indexes etc. in PostgreSQL with a very thin Ruby gem wrapper to make it accessible from a Rails app.  But still very usable as SQL/from psql only.

This is my favorite writeup so far and it's using pg_search. Just sharing extra context because I see you've been contributing to a couple of search related gems for years! Thanks!
https://pganalyze.com/blog/full-text-search-ruby-rails-postgres

**Comment by gregmolnar** [comment]
@andyatkinson I removed the references to that old documentation site, I couldn't find the source for it, I assume it was an autogenerated yard doc or something similar.
I also removed the CircleCI references from the Readme because to get a new badge snippet, I need to have access to the project there, but my account doesn't have access to it for some odd reason, and when I try to link it to it, it asks me to add it to all the open-source repositories I have access to, and I don't want that.

**Comment by andyatkinson** [comment]
Sounds good @gregmolnar 

FYI since writing earlier, I've been working with https://github.com/Casecommons/pg_search more. We have some legitimate usage at work, but I've been peeling back the layers of tsvectors, tsqueries, and how to GIN index them, and writing some educational content on using PostgreSQL FTS capabilities with Rails. Maybe we can collaborate in that area sometime.

**Comment by gregmolnar** [comment]
> Maybe we can collaborate in that area sometime.

That would be great.
