### ISSUE TITLE
Includes

### ISSUE THREAD

**Issue by nodrog** [textacular/textacular#66]
Hi 

I want to use an includes and i get an error am i doing this right:

>  #works
> @ccgs = @ccgs.advanced_search({ code: search, name: search }, false)
> #error
> @ccgs = @ccgs.includes(:local_area_team).advanced_search({ code: search, name: search, local_area_teams: { name: search } }, false)

> ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  missing FROM-clause entry for table "local_area_team"
> LINE 1: ...'''wandsworth'''::text) OR to_tsvector('english', "local_are...

I am obviously doing something stupid, but really not sure what.

Many thanks

**Comment by gregmolnar** [comment]
I guess this one is not an issue anymore, please reopen it if I am wrong.

**Comment by nodrog** [comment]
Sorry for not closing... 

We moved away from using textacular, i will see if i can dig out the sql it it would help.

thanks

**Comment by gregmolnar** [comment]
Thanks a lot @nodrog !
