### ISSUE TITLE
Search against associations (model relations)

### ISSUE THREAD

**Issue by phlegx** [textacular/textacular#70]
Do search against associated model attributes work? Given this example of models:

```ruby
class User < ActiveRecord::Base
    has_many :projects
end

class Project < ActiveRecord::Base
    belongs_to :user
    has_one :calendar
end

class Calendar < ActiveRecord::Base
    belongs_to :project
end
```

How can I perform the following search:

```ruby
search = 'Test'
User.basic_search(name: search, projects: { name: search })
Project.basic_search(name: search, user: { name: search }, calendar: { title: search })
```

**Comment by benhamill** [comment]
If I understand what you're asking, then this test should illustrate what you want? https://github.com/textacular/textacular/blob/master/spec/textacular_spec.rb#L82

If not, then can you point out the difference?

**Comment by phlegx** [comment]
@benhamill no thats it! :smile:

**Comment by phlegx** [comment]
This is not documented in the README! :cry:

**Comment by benhamill** [comment]
Glad I could help. The README is a bit unweildy, as it is. We should probably redesign it so it's easier to find stuff. And add stuff like this. But in the mean time, if someone wanted to add a section about this feature, that would be a cool PR to see. :smile:

**Comment by phlegx** [comment]
OK. Is there a way to configure textacular like in gem pg_search? I mean, so that I can configure textacular (accents, tsearch, etc.) in every model like in pg_search (https://github.com/Casecommons/pg_search#searching-using-different-search-features):

```ruby
class User < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search,
                  against: [:firstname, :lastname], associated_against: {
                    projects: :name,
                  },
                  using: { tsearch: { prefix: true, dictionary: 'en' } },
                  ignoring: :accents
...
```

  1. **:tsearch (Full Text Search)**
  2. **:prefix (PostgreSQL 8.4 and newer only)**
  3. **:negation**
  4. **:trigram (Trigram search)**
  5. etc.

**Comment by benhamill** [comment]
Nope. Textacular doesn't have a configuration feature right now. Some of that can be messed with (look at [the website]() or the tests), but not all. We see those two gems this way: Textacular is dead simple to get up and running if your needs aren't that complex. If you need to do more tweaking or whatever, then you should probably use pg_search.

**Comment by phlegx** [comment]
For the PR: I will try out some complex search with textacular first. Globalize gem is widely used gem and I want to test it with textacular. :smile:  @benhamill congratulations for the gem!
