### ISSUE TITLE
Any way to use unaccent ?

### ISSUE THREAD

**Issue by allaire** [textacular/textacular#72]
Hi there,

Is there anyway to use unaccent package with textacular? I know PG_Search is more "configurable", but Textacular looks cleaner to me and that's mostly the only feature that's missing for me (because from what I see, we can use advanced_search to do most of the things like prefix and such).

@benhamill  I'm also willing to do a PR implementing this, just need some hints before :+1: 

Thanks!

**Comment by benhamill** [comment]
I haven't used it, but skimming [the docs](http://www.postgresql.org/docs/9.4/static/unaccent.html), it looks like you could run the `ALTER TEXT SEARCH CONFIGURATION` bit shown there and it might Just Work. If not, you can post here about problems and maybe we can get it sorted out.

**Comment by allaire** [comment]
@benhamill PGSearch wraps queries with unaccent() (using a normalizing function): https://github.com/Casecommons/pg_search/blob/35b858a50aaa078fcb0ce7ae2427c5f6efca1282/lib/pg_search.rb#L24

Would something like this be possible?

**Comment by benhamill** [comment]
It would be _possible_, but I don't want to unilaterally decide to ditch diacritics. Especially if you can tell Postgres to alter the dictionary that you're using and have it work transparently from Textacular's point of view.

**Comment by allaire** [comment]
Roger that. Let me do some testting with that Postgres configuration, I'll report back. Thanks for the quick reply :beers:

**Comment by rapcal** [comment]
I know this one is old and already closed, but if anyone stumbles upon this issue, altering text search configuration as suggested by @benhamill works like a charm. A Rails migration to perform unaccented searches in the german language, for instance, would look something like this:

````ruby
def up
  execute "
    CREATE TEXT SEARCH CONFIGURATION de ( COPY = german );
    ALTER TEXT SEARCH CONFIGURATION de
    ALTER MAPPING FOR hword, hword_part, word
    WITH unaccent, german_stem;
    "
end
def down
  execute "
    DROP TEXT SEARCH CONFIGURATION pt;
  "
end
