### ISSUE TITLE
Indexing and sql schema

### ISSUE THREAD

**Issue by Ajaxy** [textacular/textacular#74]
It seems not good for me to change schema format to `sql`. That `ruby` one is much more clear and intuitive. Is there some way to keep on going with it? Maybe manually add that `execute ...` code into the schema where all other indexes are?

Thanks in advance.

**Comment by benhamill** [comment]
Personally, I've never really worried about the schema being readable. It's there mostly to support `rake db:setup` and similar. You could, indeed, add an `execute` section, but as the schema's meant to be generated and will be every time you run a new migration, you'd probably lose it soon after.

You could consider adding a new dependent task to things like `rake db:setup` that would run that one migration to add the index and hard-code it in the rake task. But you'd have to do some research to figure out how and how well that works.

Sorry I'm not more help.

**Comment by Ajaxy** [comment]
Thank you, then closing.
