### ISSUE TITLE
Negation operator "!" escaping issue using advanced_search method

### ISSUE THREAD

**Issue by naysayer** [textacular/textacular#76]
Right out of the box I am not having issues with using using the AND (&) or the OR (|) operator with the advanced search method. The following works great:

    Keyword.advanced_search("foo|bar") 
    or 
    Keyword.advanced_search("foo & bar")

Negation by itself also works great: 

    Keyword.advanced_search("!baz")

However when combining negation with any other type of query param returns the following pg syntax error:

    Keyword.advanced_search("foo !bar")

PG::SyntaxError: ERROR:  syntax error in tsquery: "foo\ !bar"
: SELECT "keywords".*, COALESCE(ts_rank(to_tsvector('english', "keywords"."keyword"::text), to_tsquery('english', 'foo\ !bar'::text)), 0) AS "rank89557751754006092" FROM "keywords" WHERE (to_tsvector('english', "keywords"."keyword"::text) @@ to_tsquery('english', 'foo\ !bar'::text))  ORDER BY "rank89557751754006092" DESC

As stated in the ReadMe, I have checked the postgresql docs, and I notice that the query generated by the textacular gem adds a \ ad the at the end of each word within the query, where as the postgres documentation gives examples of this type of query without the \. Do I simply need to escape the type of query I am trying to preform? I have checked the documentation for the this gem and have not found any reference to it, and how would I go about escaping it properly? Thanks in advance.

**Comment by benhamill** [comment]
This feature is actually pretty poorly tested and, I think, little used. If you run the query against your DB raw, but take out the `\`, does it work as expected?

Any other maintainers know why the `\` was originally put in there? I don't understand `to_tsquery` super well.

**Comment by gregmolnar** [comment]
@benhamill it doesn't work without the `\` because that syntax is invalid.
@naysayer where did you see that example in the postgres docs?

**Comment by gregmolnar** [comment]
I was wrong, it is valid syntax without the backslash. I sort of see where the problem is and trying to fix it.
