### ISSUE TITLE
What's the reasoning behind not exposing the rank score with a static name?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [textacular/textacular#88]
I would really like to access the rank to make some after filtering in ruby. But the ranking score when using `fuzzy_search` got strange unpredictable names like: `rank65980239733176812`. Why is this?

https://github.com/textacular/textacular/pull/89

**Comment by MiroBabic** [comment]
I would also like to use that rank value in further process. Is it possible to name rank value just with some static name like "textacular-rank" ?
thanks

**Comment by simi** [comment]
see the reason in original commit introducing this https://github.com/textacular/textacular/commit/2d5fc5c19e3ee4e106f5b8f1f4f47018556c2274

**Comment by gregmolnar** [comment]
Thanks to @simi now you can use a custom name for the rank score and access it by that.
