### ISSUE TITLE
Current 4.0.0 gem prevents upgrading to Rails 5.0.0.1

### ISSUE THREAD

**Issue by chrisnicola** [textacular/textacular#95]
The gemspec in master has been fixed but a Gem release is still needed to avoid having to reference the master branch or Github commit directly.

**Comment by Paxa** [comment]
Would be nice to make new release with rails 5 support

**Comment by gregmolnar** [comment]
I will do a release this week

**Comment by gregmolnar** [comment]
I pushed a new release to rubygems. Thanks for the patience :)
